improve tor-controller to specify less options
https://github.com/nyxnor/tor-controller/issues/2

diff --git a/bin/tor-controller b/bin/tor-controller
--- a/bin/tor-controller
+++ b/bin/tor-controller
@@ -59,33 +59,25 @@ usage(){
 
   -c [command]   command to execute
                  notice: always \"double quote\" your command
+                 notice: separate control commands with a pipe '|'
 
-  -f [file]      file to execute commands from
-                 notice: only one command per line
-
-  -C [path]      path to tor's control socket
-                 default: /run/tor/control
-                 notice: do not forget to adjust your torrc
-
-  -a [path]      path to tor's control_auth_cookie
-                 default: found via PROTOCOLINFO command, COOKIEFILE=/path
-                 notice: do not forget to adjust your torrc
-
-  -P [port]      tor ControlPort
+  -C [socket]    tor's control socket
                  default: 9051
+                 notice: tcp: [addr:]port: 9051, 127.0.0.1:9051
+                 notice: unix: /run/tor/control, unix:/run/tor/control
 
   -p [pwd]       use password [var] instead of Tor's control_auth_cookie
                  default: not used
-                 notice: do not forget to adjust your torrc
 
   -s [time]      sleep [var] seconds after each command sent
-                 default: 1 second
+                 default: 0 second
+                 notice: if the socket program is telnet, fallback to 1 second
                  notice: for GETCONF, you can use smaller pause times
-                 than for SETCONF; this is due to telnet's behavior.
+                 than for SETCONF; this is due to telnet's behavior
 
-  -w             wait to read confirmation (ENTER) before closing the connection.
+  -w             wait to read confirmation by pressing and ENTER before closing the connection
                  default: not set
-                 notice: useful when listening for events
+                 notice: useful when you want to be informed about events
 
   -v             verbose
                  default: not set
@@ -93,12 +85,18 @@ usage(){
                  You probably want to set -v when running manually
 
   Examples:      ${me} -c \"SETCONF bandwidthrate=1mb\"
-                 ${me} -v -s 0 -c \"GETCONF User\"
-                 ${me} -v -s 0 -P 9051 -p foobar -c \"GETCONF bandwidthrate\"
-                 ${me} -s 0 -v -w -c \"SETEVENTS STREAM\"
+                 ${me} -v -P 9051 -p foobar -c \"GETCONF bandwidthrate\"
+                 ${me} -v -c \"GETINFO config-defaults-file config-file config-text\"
+                 ${me} -v -c \"GETCONF SocksPort | GETINFO net/listeners/socks\"
+                 ${me} -v -w -c \"SETEVENTS STREAM\"
 
 You should have a look at
 https://gitweb.torproject.org/torspec.git/tree/control-spec.txt"
+  exit 1
+}
+
+error_msg(){
+  printf %s"${me}: ${1}\n"
   exit 1
 }
 
@@ -110,36 +108,35 @@ checkprogs(){
     done
     break
   done
-  if [ -z "${socket_prog}" ]; then
-    printf '%s\n' "Install one of the following programs to connect to sockets: ${prog_net}"
-    exit 1
-  fi
+  [ -z "${socket_prog}" ] && error_msg "Install one of the following programs to connect to sockets: ${prog_net}"
+
+  case "${socket_prog}" in
+    telnet) sleep_n=1;;
+    *) : "${sleep_n:=0}";;
+  esac
 
   case "${socket_type}" in
     unix)
-      if [ ! -f "${tor_control_unix}" ]; then
-        printf '%s\n' "Couldn't find ControlSocket ${tor_control_unix}"
-        exit 1
-      fi
+      [ ! -S "${tor_control_unix}" ] && error_msg "${tor_control_unix} doesn't exist"
       case "${socket_prog##*/}" in
         nc|netcat) socket_prog="${socket_prog} -U ${tor_control_unix}";;
         socat) socket_prog="${socket_prog} - UNIX-CONNECT:${tor_control_unix}";;
-        telnet) printf "Telnet doesn't support unix domain sockets"; exit 1;;
+        telnet) error_msg "Telnet doesn't support unix domain sockets";;
       esac
     ;;
     tcp)
       case "${socket_prog##*/}" in
         nc|netcat)
-          ${socket_prog} -z "${tor_control_host}" "${tor_control_port}" || { printf '%s\n' "Connetion refused to ControlPort ${tor_control_host}:${tor_control_port}"; exit 1; }
+          "${socket_prog}" -z "${tor_control_host}" "${tor_control_port}" || error_msg "${socket_prog}: Connetion refused to ${tor_control_host}:${tor_control_port}"
           socket_prog="${socket_prog} ${tor_control_host} ${tor_control_port}"
         ;;
         socat)
-          ${socket_prog} /dev/null TCP:"${tor_control_host}:${tor_control_port}" || { printf '%s\n' "Connetion refused to ControlPort ${tor_control_host}:${tor_control_port}"; exit 1; }
+          "${socket_prog}" /dev/null TCP:"${tor_control_host}:${tor_control_port}" || error_msg "${socket_prog}: Connetion refused to ${tor_control_host}:${tor_control_port}"
           socket_prog="${socket_prog} - TCP:${tor_control_host}:${tor_control_port}"
         ;;
         telnet)
-          printf "\x1dclose\x0d" | ${socket_prog} "${tor_control_host}" "${tor_control_port}" || { printf '%s\n' "Connetion refused to ControlPort ${tor_control_host}:${tor_control_port}"; exit 1; }
-          socket_prog="${socket_prog} ${tor_control_host} ${tor_control_port} 2>/dev/null"
+          ##printf "\x1dclose\x0d" | "${socket_prog}" "${tor_control_host}" "${tor_control_port}" >/dev/null 2>&1 || error_msg "${socket_prog}: Connetion refused to ${tor_control_host}:${tor_control_port}"
+          socket_prog="${socket_prog} ${tor_control_host} ${tor_control_port}"
         ;;
         # bash)
         #   bash -c "{ printf '%s\n%s\n' \"PROTOCOLINFO\" \"QUIT\" >&3; cat <&3 ; } 3<> /dev/tcp/${tor_control_host}/${tor_control_port}"
@@ -162,110 +159,111 @@ login(){
 
   hashedpassword_enabled="$(printf '%s\n' "${auth_methods}" | grep "^HASHEDPASSWORD$")"
   tor_cookie="$(printf '%s\n' "${auth}" | sed "s/.*COOKIEFILE=//" | tr -d "\"" | tr -d "\\r")"
-  if [ -n "${tor_cookie}" ] && [ -f "${tor_cookie}" ]; then
-    #cookie_string="$(xxd -u -p -c 32 "${tor_cookie}")"
-    #safecookie_enabled="$(printf '%s\n' "${auth_methods}" | grep "^SAFECOOKIE$")"
+  if test -r "${tor_cookie}"; then
+    safecookie_enabled="$(printf '%s\n' "${auth_methods}" | grep "^SAFECOOKIE$")"
     cookie_enabled="$(printf '%s\n' "${auth_methods}" | grep "^COOKIE$")"
-  fi
-
-  # if [ -n "${safecookie_enabled}" ] && test -f "${tor_cookie}" && command -v xxd >/dev/null && test -c /dev/urandom; then
-  #   authchallenge_string="AUTHCHALLENGE SAFECOOKIE ${client_nonce}"
-  if [ -n "${cookie_enabled}" ] && test -f "${tor_cookie}"; then
-    ## xxd is only needed when authenticating with SAFECOOKIE
-    while :; do
-      command -v xxd >/dev/null && hex_prog="xxd" && break
-      command -v hexdump >/dev/null && hex_prog="hexdump" && break
-      command -v od >/dev/null && hex_prog="od" && break
-      break
-    done
-    case "${hex_prog}" in
-      xxd) auth_string="AUTHENTICATE $(xxd -u -p -c 32 "${tor_cookie}")";;
-      hexdump) auth_string="AUTHENTICATE $(hexdump -e '32/1 "%02x""\n"' "${tor_cookie}")";;
-      od) auth_string="AUTHENTICATE $(od -t x1 "${tor_cookie}" | head -n 2 | cut -d " " -f2- | tr -d "\n" | tr -d " ")";;
-      *) printf "Missing program to dump hex. Install either 'hexdump' or 'xxd' or 'od'."
-    esac
-  elif [ -n "${hashedpassword_enabled}" ] && [ -z "${tor_cookie}" ] && [ -n "${tor_password}" ]; then
+    if [ -n "${cookie_enabled}" ]; then
+      ## xxd is only needed when authenticating with SAFECOOKIE
+      while :; do
+        command -v xxd >/dev/null && hex_prog="xxd" && break
+        command -v hexdump >/dev/null && hex_prog="hexdump" && break
+        command -v od >/dev/null && hex_prog="od" && break
+        break
+      done
+      case "${hex_prog}" in
+        xxd) auth_string="AUTHENTICATE $(xxd -u -p -c 32 "${tor_cookie}")";;
+        hexdump) auth_string="AUTHENTICATE $(hexdump -e '32/1 "%02x""\n"' "${tor_cookie}")";;
+        od) auth_string="AUTHENTICATE $(od -t x1 "${tor_cookie}" | head -n 2 | cut -d " " -f2- | tr -d "\n" | tr -d " ")";;
+        *) printf "Missing program to dump hex. Install either 'hexdump' or 'xxd' or 'od'."
+      esac
+    fi
+  elif [ -n "${hashedpassword_enabled}" ] && [ -n "${tor_password}" ]; then
     auth_string="AUTHENTICATE \"${tor_password}\""
   fi
 }
 
 sendcmd(){
-  printf '%s\n' "${1}" 1>&3
+  printf '%s\n' "${1}" >&3
+  sleep "${sleep_n}"
 }
 
 finish(){
   sendcmd "QUIT"
-  str="$(cat <&3 2>/dev/null)"
+  #exec 0<&3
+  #str="$(cat)"
+  str="$(exec 0<&3 cat)"
+  #str="$(cat <&3 2>/dev/null)"
   [ "${verbose}" -ge 1 ] && printf '%s\n' "${str}"
   printf '%s\n' "${str}" | { [ "$(grep -c "^250 ")" != 3 ] && exit 1; }
 }
 
-filepipe(){
-  while read -r line; do
-    sendcmd "${line}"
-  done < "${1}"
-  sendcmd "QUIT"
-}
 
-
-while getopts ":a:c:C:s:p:P:f:wvh" Option; do
+while getopts ":c:C:s:p:vwh" Option; do
   case ${Option} in
     c) cmd_cli="${OPTARG}";;
-    f) cmd_file="${OPTARG}";;
-    a) tor_cookie="${OPTARG}";;
-    p) tor_password="${OPTARG}";;
-    C) tor_control_unix="${OPTARG}";;
-    P) tor_control_port="${OPTARG}";;
+    C) tor_control="${OPTARG}";;
     s) sleep_n="${OPTARG}";;
-    w) wait_confirmation=1;;
+    p) tor_password="${OPTARG}";;
     v) verbose=1;;
+    w) wait_confirmation=1;;
     h|*) usage;;
   esac
 done
 
 
-## if ControlSocket is not given (unix domain socket)
-## fallback to ControlPort 127.0.0.1:9051 (tcp socket)
-case "${tor_control_unix}" in
-  "") socket_type="tcp";;
-  *) socket_type="unix";;
+: "${verbose:=0}"
+
+## accept commands separated by pipes
+cmd_cli="$(printf '%s\n' "${cmd_cli}" | tr -s "|" "\n" | sed "s|^ ||")"
+
+
+## find if tor_control is a socket or add:port and do sanity checks
+case "${tor_control}" in
+  "unix:/"*|"/"*)
+    socket_type="unix"
+    tor_control_unix="${tor_control##*unix:}"
+    test -e "${tor_control_unix}" || error_msg "${tor_control_unix} does not exist"
+    test -S "${tor_control_unix}" || error_msg "${tor_control_unix} is not a socket"
+  ;;
+  [0-9]*)
+    socket_type="tcp"
+    tor_control_port="${tor_control##*:}"
+    tor_control_port="${tor_control_port:-9051}"
+    printf %d "${tor_control_port}" >/dev/null 2>&1 || error_msg "${tor_control_port} is not a valid port, not an integer"
+    { [ "${tor_control_port}" -gt 0 ] && [ "${tor_control_port}" -le 65535 ]; } || error_msg "${tor_control_port} is not a valid port, not within range: 0-65535"
+    tor_control_host="${tor_control%%:*}"
+    [ "${tor_control_host}" = "${tor_control_port}" ] && tor_control_host="127.0.0.1"
+    for quad in $(printf '%s\n' "${tor_control_host}" | tr "." " "); do
+      printf %d "${quad}" >/dev/null 2>&1 || error_msg "${tor_control_host} is not a valid address, ${quad} is not and integer"
+      { [ "${quad}" -ge 0 ] && [ "${quad}" -le 255 ]; } || error_msg "${tor_control_host}is not a valid address, ${quad} is not within range: 0-255"
+    done
+  ;;
 esac
 
-: "${sleep_n:=1}"
-: "${verbose:=0}"
-: "${tor_control_port:=9051}"
-tor_control_host="${tor_control_port%%:*}"
-tor_control_port="${tor_control_port##*:}"
-[ "${tor_control_host}" = "${tor_control_port}" ] && tor_control_host="127.0.0.1"
-
-
-## main
-
-if [ -e "${cmd_file}" ]; then
-  checkprogs
-  login
-  { sendcmd "${auth_string}"; filepipe "${cmd_cli}"; finish; } | ${socket_prog}
-fi
+############
+### main ###
 
 if [ -n "${cmd_cli}" ]; then
   checkprogs
   login
-  # if [ -n "${safecookie_enabled}" ] && test -f "${tor_cookie}" && command -v xxd >/dev/null && test -c /dev/urandom; then
-  #   {
-  #     ## TODO server_nonce is not working, how to solve a challenge and continue answering the server?
-  #     client_nonce="$(xxd -u -p -c 32 -l 32 /dev/urandom)"
-  #     #sendcmd "AUTHCHALLENGE SAFECOOKIE ${client_nonce}"
-  #     server_nonce="$(sendcmd "AUTHCHALLENGE SAFECOOKIE ${client_nonce}")"
-  #     #server_nonce="$(printf '%s\n' "$(sendcmd "AUTHCHALLENGE SAFECOOKIE ${client_nonce}" 3>&1)" | sed "s/.* SERVERNONCE=//" | tr -d "\\r")"
-  #     #sendcmd "AUTHENTICATE $(sendcmd "AUTHCHALLENGE SAFECOOKIE ${client_nonce}" | sed "s/.* SERVERNONCE=//" | tr -d "\\r")"
-  #     #sendcmd "AUTHENTICATE $(printf '%s%s%s\n' "${cookie_string}" "${client_nonce}" "$(sendcmd "AUTHCHALLENGE SAFECOOKIE ${client_nonce}")" | xxd -r -p | openssl dgst -sha256 -binary -hmac "Tor safe cookie authentication controller-to-server hash" | xxd -p -u -c 32)"
-  #     # shellcheck disable=SC2030
-  #     #echo "server_nonce=${server_nonce}" && sendcmd "QUIT" && exit 1
-  #     sendcmd "AUTHENTICATE $(printf '%s%s%s\n' "${cookie_string}" "${client_nonce}" "${server_nonce}" | xxd -r -p | openssl dgst -sha256 -binary -hmac "Tor safe cookie authentication controller-to-server hash" | xxd -p -u -c 32)"
-  #     sendcmd "${cmd_cli}"
-  #     finish
-  #   } 3>&1 | ${socket_prog}
-  # else
+  ## disable safecookie as it is not working https://github.com/nyxnor/tor-controller/issues/1
+  safecookie_enabled=""
+  if [ -n "${safecookie_enabled}" ] && test -r "${tor_cookie}" && command -v xxd >/dev/null && test -c /dev/urandom; then
+    {
+      cookie_string="$(xxd -u -p -c 32 "${tor_cookie}")"
+      client_nonce="$(xxd -u -p -l 32 -c 32 < /dev/urandom)"
+      ## TODO server_nonce is not working, how to solve a challenge and continue answering the server?
+      #sendcmd "AUTHCHALLENGE SAFECOOKIE ${client_nonce}"
+      server_nonce="$(sendcmd "AUTHCHALLENGE SAFECOOKIE ${client_nonce}")"
+      server_nonce="$(printf '%s\n' "${server_nonce}" | sed "s/.* SERVERNONCE=//" | tr -d "\\r")"
+      #server_nonce="$(printf '%s\n' "$(sendcmd "AUTHCHALLENGE SAFECOOKIE ${client_nonce}" 3>&1)" | sed "s/.* SERVERNONCE=//" | tr -d "\\r")"
+      # shellcheck disable=SC2030
+      auth_string="AUTHENTICATE $(printf '%s%s%s\n' "${cookie_string}" "${client_nonce}" "${server_nonce}" | xxd -r -p | openssl dgst -sha256 -binary -hmac "Tor safe cookie authentication controller-to-server hash" | xxd -p -u -c 32)"
+      sendcmd "${auth_string}"
+      sendcmd "${cmd_cli}"
+      finish
+    } 3>&1 | ${socket_prog}
+  else
     {
       # shellcheck disable=SC2030,2031
       sendcmd "${auth_string}"
@@ -273,8 +271,8 @@ if [ -n "${cmd_cli}" ]; then
       # shellcheck disable=SC2034
       [ -n "${wait_confirmation}" ] && read -r confirmation
       finish
-    } 3>&1 | ${socket_prog}
-  # fi
+    } 3>&1 2>/dev/null | ${socket_prog}
+  fi
 else
   usage
 fi
