show streams before pressing enter
fix for tor-ctrl and tor-ctrl-stream. Unfortunately, on tor-ctrl-stream, I couldn't find a way to print the streams at the same time as saving them, it is closing the connection if I send the process to background with '$ tor-ctrl -w SETEVENTS STREAM &', so looping GETINFO stream-status is the workaround.

diff --git a/usr/bin/tor-ctrl b/usr/bin/tor-ctrl
--- a/usr/bin/tor-ctrl
+++ b/usr/bin/tor-ctrl
@@ -62,6 +62,7 @@ usage(){
 
   -w             wait to read confirmation by pressing ENTER before closing the connection
                  notice: useful when you want to be informed about events (asynchronous replies)
+                 notice: incompatible with '-q' - quiet mode.
                  default: not set
 
   -q             quiet mode.
@@ -259,8 +260,11 @@ get_dry_run(){
 
 ## send command to the controller and sleep after it if required
 send_cmd(){
-  printf '%s\n' "${1}"
-  sleep "${sleep_n}"
+  ## avoid sending empty lines and cycle sleep for every line sent if cmd_cli has multiple lines
+  printf '%s\n' "${1}" | while IFS="$(printf '\n')" read -r line || [ -n "${line}" ]; do
+    printf '%s\n' "${line}"
+    sleep "${sleep_n}"
+  done
 }
 
 ## piping commands to be sent
@@ -268,7 +272,7 @@ cmd_pipe(){
   # shellcheck disable=SC2030,2031
   send_cmd "${auth_string}"
   send_cmd "${cmd_cli}"
-  # shellcheck disable=SC2034
+  ## shellcheck disable=SC2034
   [ "${wait_confirmation}" -eq 1 ] && read -r confirmation
   send_cmd "QUIT"
 }
@@ -277,7 +281,8 @@ cmd_pipe(){
 finish(){
   str="$(cat)"
   [ "${quiet}" -eq 0 ] && printf '%s\n' "${str}"
-  printf '%s\n' "${str}" | if [ "$(grep -c ^"250 ")" = 3 ]; then
+  ## more than 3 '^250 ' reply status code occurs when $cmd_cli has multiple lines (\\n)
+  printf '%s\n' "${str}" | if [ "$(grep -c "^250 ")" -ge 3 ]; then
     exit 0
   else
     exit 1
@@ -289,15 +294,12 @@ finish(){
 
 ## if option requires argument, check if it was provided, if yes, assign the arg to the opt
 get_arg(){
+  ## if argument is empty or starts with '-', fail as it possibly is an option
   case "${arg}" in
     ""|-*) error_msg "Option '${opt}' requires an argument.";;
   esac
-
-  case "${arg}" in
-    -*) value="${arg#-}";;
-    *) value="${arg}"
-  esac
-  ## Escaping quotes is needed because else fail if the argument is quoted
+  value="${arg}"
+  ## Escaping quotes is needed because else it will fail if the argument is quoted
   # shellcheck disable=SC2140
   eval "${1}"="\"${value}\""
 }
@@ -345,6 +347,10 @@ if [ -n "${cmd_cli}" ]; then
   cmd_cli="$(printf %s"${cmd_cli}\n" | sed "s|^ ||")"
   ## check if requirements are fulfilled
   check_progs
+  ## sleep was assigned on check_progs if empty because of telnet, see if it is valid.
+  if ! printf '%d' "${sleep_n}" >/dev/null 2>&1 && ! printf '%g' "${sleep_n}" >/dev/null 2>&1; then
+    error_msg "Sleep time '${sleep_n}' is not an integer nor a floating point."
+  fi
   ## if socket was not assigned on the command line, try auto-detection
   [ -z "${tor_control_socket}" ] && get_socket
   ## just get variables, don't send commands to the controller
@@ -356,7 +362,7 @@ if [ -n "${cmd_cli}" ]; then
 
   ## disable safecookie as it is not working https://github.com/nyxnor/tor-ctrl/issues/1
   safecookie_enabled=""
-  if [ -n "${safecookie_enabled}" ] && test -r "${tor_cookie}" && command -v xxd >/dev/null && test -c /dev/urandom; then
+  if [ -n "${safecookie_enabled}" ] && test -r "${tor_cookie}" && has xxd && test -c /dev/urandom; then
     {
       cookie_string="$(xxd -u -p -c 32 "${tor_cookie}")"
       client_nonce="$(xxd -u -p -l 32 -c 32 < /dev/urandom)"
@@ -371,10 +377,14 @@ if [ -n "${cmd_cli}" ]; then
       send_cmd "${cmd_cli}"
       # shellcheck disable=SC2034
       [ -n "${wait_confirmation}" ] && read -r confirmation
-      send_cmd "QUIT"
+      #send_cmd "QUIT"
     } 3>&1 2>/dev/null | ${socket_prog_connect} | finish
   else
-    cmd_pipe | ${socket_prog_connect} 2>/dev/null | finish
+    if [ "${wait_confirmation}" -eq 1 ]; then
+      cmd_pipe | ${socket_prog_connect} 2>/dev/null
+    else
+      cmd_pipe | ${socket_prog_connect} 2>/dev/null | finish
+    fi
   fi
 else
   usage
