make temporary file be created on tmpdir
avoid putitng files on current directory

diff --git a/usr/bin/tor-ctrl b/usr/bin/tor-ctrl
--- a/usr/bin/tor-ctrl
+++ b/usr/bin/tor-ctrl
@@ -176,25 +176,34 @@ check_socket(){
     "unix:/"*|"/"*)
       socket_type="unix"
       tor_control_unix="${socket##*unix:}"
-      test -e "${tor_control_unix}" || { printf '%s\n' "${tor_control_unix} does not exist" | tee -a fail.log >/dev/null; return 1; }
-      test -S "${tor_control_unix}" || { printf '%s\n' "${tor_control_unix} is not a socket" | tee -a fail.log >/dev/null; return 1; }
+      test -e "${tor_control_unix}" || {
+        printf '%s\n' "${tor_control_unix} does not exist" | tee -a "${tmpdir}"/fail.log >/dev/null
+        return 1
+      }
+      test -S "${tor_control_unix}" || {
+        printf '%s\n' "${tor_control_unix} is not a socket" | tee -a "${tmpdir}"/fail.log >/dev/null
+        return 1
+      }
     ;;
     [0-9]*|":"[0-9]*)
       ## latter option occurs when TOR_CONTROL_HOST is empty but TOR_CONTROL_PORT is not
       socket_type="tcp"
       tor_control_port="${socket##*:}"
       tor_control_port="${tor_control_port:-9051}"
-      printf %d "${tor_control_port}" >/dev/null 2>&1 || { printf '%s\n' "${tor_control_port} is not a valid port, not an integer" | tee -a fail.log >/dev/null; return 1; }
-      { [ "${tor_control_port}" -gt 0 ] && [ "${tor_control_port}" -le 65535 ]; } || { printf '%s\n' "${tor_control_port} is not a valid port, not within range: 0-65535" | tee -a fail.log >/dev/null; return 1; }
+      printf %d "${tor_control_port}" >/dev/null 2>&1 || {
+        printf '%s\n' "${tor_control_port} is not a valid port, not an integer" | tee -a "${tmpdir}"/fail.log >/dev/null
+        return 1
+      }
+      { [ "${tor_control_port}" -gt 0 ] && [ "${tor_control_port}" -le 65535 ]; } || { printf '%s\n' "${tor_control_port} is not a valid port, not within range: 0-65535" | tee -a "${tmpdir}"/fail.log >/dev/null; return 1; }
       tor_control_host="${socket%%:*}"
       { [ "${tor_control_host}" = "${tor_control_port}" ] || [ -z "${tor_control_host}" ]; } && tor_control_host="127.0.0.1"
       for quad in $(printf '%s\n' "${tor_control_host}" | tr "." " "); do
-        printf %d "${quad}" >/dev/null 2>&1 || { printf '%s\n' "${tor_control_host} is not a valid address, ${quad} is not and integer" | tee -a fail.log >/dev/null; return 1; }
-        { [ "${quad}" -ge 0 ] && [ "${quad}" -le 255 ]; } || { printf '%s\n' "${tor_control_host} is not a valid address, ${quad} is not within range: 0-255" | tee -a fail.log >/dev/null; return 1; }
+        printf %d "${quad}" >/dev/null 2>&1 || { printf '%s\n' "${tor_control_host} is not a valid address, ${quad} is not and integer" | tee -a "${tmpdir}"/fail.log >/dev/null; return 1; }
+        { [ "${quad}" -ge 0 ] && [ "${quad}" -le 255 ]; } || { printf '%s\n' "${tor_control_host} is not a valid address, ${quad} is not within range: 0-255" | tee -a "${tmpdir}"/fail.log >/dev/null; return 1; }
       done
     ;;
     ":") return 1;; ## this happens when variables are empty
-    *) printf '%s\n' "socket '${socket}' is invalid" | tee -a fail.log >/dev/null; return 1;;
+    *) printf '%s\n' "socket '${socket}' is invalid" | tee -a "${tmpdir}"/fail.log >/dev/null; return 1;;
   esac
 
   ## assign the program options for socket and test if conneciton is refused
@@ -203,13 +212,13 @@ check_socket(){
       case "${socket_prog##*/}" in
         nc|netcat)
           socket_prog_connect="${socket_prog} -U ${tor_control_unix}"
-          ${socket_prog_connect} -zv || { printf '%s\n' "${socket_prog}: Connetion refused to ${tor_control_unix}" | tee -a fail.log >/dev/null; return 1; }
+          ${socket_prog_connect} -zv || { printf '%s\n' "${socket_prog}: Connetion refused to ${tor_control_unix}" | tee -a "${tmpdir}"/fail.log >/dev/null; return 1; }
         ;;
         socat)
           socket_prog_connect="${socket_prog} - UNIX-CONNECT:${tor_control_unix}"
-          ${socket_prog} /dev/null "UNIX-CONNECT:${tor_control_unix}" || { printf '%s\n' "${socket_prog}: Connetion refused to ${tor_control_unix}" | tee -a fail.log >/dev/null; return 1; }
+          ${socket_prog} /dev/null "UNIX-CONNECT:${tor_control_unix}" || { printf '%s\n' "${socket_prog}: Connetion refused to ${tor_control_unix}" | tee -a "${tmpdir}"/fail.log >/dev/null; return 1; }
         ;;
-        *) printf '%s\n' "${socket_prog##*/} doesn't support Unix-domain sockets" | tee -a fail.log >/dev/null; return 1;;
+        *) printf '%s\n' "${socket_prog##*/} doesn't support Unix-domain sockets" | tee -a "${tmpdir}"/fail.log >/dev/null; return 1;;
       esac
 
       tor_socket="${tor_control_unix}"
@@ -218,15 +227,15 @@ check_socket(){
       case "${socket_prog##*/}" in
         nc|netcat)
           socket_prog_connect="${socket_prog} ${tor_control_host} ${tor_control_port}"
-          ${socket_prog_connect} -z || { printf '%s\n' "${socket_prog}: Connetion refused to ${tor_control_host}:${tor_control_port}" | tee -a fail.log >/dev/null; return 1; }
+          ${socket_prog_connect} -z || { printf '%s\n' "${socket_prog}: Connetion refused to ${tor_control_host}:${tor_control_port}" | tee -a "${tmpdir}"/fail.log >/dev/null; return 1; }
         ;;
         socat)
           socket_prog_connect="${socket_prog} TCP:${tor_control_host}:${tor_control_port} -"
-          "${socket_prog}" "TCP:${tor_control_host}:${tor_control_port}" /dev/null || { printf '%s\n' "${socket_prog}: Connetion refused to ${tor_control_host}:${tor_control_port}" | tee -a fail.log >/dev/null; return 1; }
+          "${socket_prog}" "TCP:${tor_control_host}:${tor_control_port}" /dev/null || { printf '%s\n' "${socket_prog}: Connetion refused to ${tor_control_host}:${tor_control_port}" | tee -a "${tmpdir}"/fail.log >/dev/null; return 1; }
         ;;
         telnet)
           socket_prog_connect="${socket_prog} ${tor_control_host} ${tor_control_port}"
-          printf "\x1dclose\x0d" | ${socket_prog_connect} 2>/dev/null | grep -q "Connected to ${tor_control_host}" || { printf '%s\n' "${socket_prog}: Connetion refused to ${tor_control_host}:${tor_control_port}" | tee -a fail.log >/dev/null; return 1; }
+          printf "\x1dclose\x0d" | ${socket_prog_connect} 2>/dev/null | grep -q "Connected to ${tor_control_host}" || { printf '%s\n' "${socket_prog}: Connetion refused to ${tor_control_host}:${tor_control_port}" | tee -a "${tmpdir}"/fail.log >/dev/null; return 1; }
         ;;
       esac
 
@@ -371,6 +380,9 @@ done
 
 ############
 ### main ###
+: "${TMPDIR:="/tmp"}"
+mkdir -p "${TMPDIR}/tor-ctrl" || error_msg "Failed to create '${TMPDIR}/tor-ctrl'"
+tmpdir="$(mktemp -d ${TMPDIR}/tor-ctrl/XXXXXX)"
 
 # sig_intr="$(stty -a | sed -n '/.*intr = / {s///;s/;.*$//;s/\^//p;}')"
 # sig_quit="$(stty -a | sed -n '/.*quit = / {s///;s/;.*$//;s/\^//p;}')"
@@ -393,7 +405,7 @@ if [ -n "${cmd_cli}" ]; then
     error_msg "Sleep time '${sleep_n}' is not an integer nor a floating point."
   fi
   ## set options for the socket program
-  trap 'rm -f fail.log' EXIT INT TERM
+  trap 'rm -f "${tmpdir}"/fail.log' EXIT INT TERM
   if [ -n "${tor_control_socket}" ]; then
     notice "attempting to connect to specified socket ${tor_control_socket}"
     check_socket "${tor_control_socket}" && socket_found=1
@@ -407,7 +419,7 @@ if [ -n "${cmd_cli}" ]; then
       while :; do
         notice "attempting to connect to fallback socket 127.0.0.1:9151"
         check_socket "127.0.0.1:9151" && break
-        error_msg "couldn't connect to Tor Browser Bundle socket. Error logs:\n$(cat fail.log)"
+        error_msg "couldn't connect to Tor Browser Bundle socket. Error logs:\n$(cat "${tmpdir}"/fail.log)"
       done
     else
       while :; do
@@ -418,11 +430,11 @@ if [ -n "${cmd_cli}" ]; then
         fi
         notice "attempting to connect to fallback socket 127.0.0.1:9051"
         check_socket "127.0.0.1:9051" && break
-        error_msg "couldn't connect to tor daemon socket. Error logs:\n$(cat fail.log)"
+        error_msg "couldn't connect to tor daemon socket. Error logs:\n$(cat "${tmpdir}"/fail.log)"
       done
     fi
   fi
-  rm -f fail.log
+  rm -f "${tmpdir}"/fail.log
 
   ## just get variables, don't send commands to the controller
   [ "${dry_run}" = "1" ] && get_dry_run
